package algorithms;

public enum DIRECTION {
Up , Down , Left , Right , Root
}

/*
1   2   3
8   5   6
4   7   0

        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: LEFT
        Client move: LEFT
        Client move: DOWN
        Client move: DOWN
        Client move: RIGHT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: DOWN
        Client move: LEFT
        Client move: UP
        Client move: UP
        Client move: RIGHT
        Client move: DOWN
        Client move: LEFT
        Client move: DOWN
        Client move: RIGHT*/
